In [3]:
!python -m pip install pandas numpy jupyter ipykernel

Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: ipykernel in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (7.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from pandas) (2026.4)
Collecting notebook (from jupyter)
  Downloading notebook-7.6.3-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Using cached nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-8.1.9-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.6.4-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: comm>=0.1.1 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (1.8.22)
Requirement already satisfied: ipython>=7.23.1 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (9.17.1)
Requirement already satisfied: jupyter-client>=8.9.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (8.10.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (1.7.3)
Requirement already satisfied: packaging>=22 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (26.3)
Requirement already satisfied: psutil>=5.7 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (27.2.0)
Requirement already satisfied: tornado>=6.4.1 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (6.5.10)
Requirement already satisfied: traitlets>=5.4.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipykernel) (5.16.1)
Requirement already satisfied: colorama>=0.4.4 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.53)
Requirement already satisfied: pygments>=2.14.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.9.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: typing-extensions>=4.13.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from jupyter-client>=8.9.0->ipykernel) (4.16.0)
Requirement already satisfied: platformdirs>=2.5 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.11.12)
Requirement already satisfied: six>=1.5 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.2)
Requirement already satisfied: pure-eval in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.4)
Collecting widgetsnbextension~=4.0.16 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-4.0.16-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.17 (from ipywidgets->jupyter)
  Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl.metadata (20 kB)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Using cached async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab->jupyter)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jinja2>=3.0.3 (from jupyterlab->jupyter)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-builder>=1.0.2 (from jupyterlab->jupyter)
  Downloading jupyter_builder-1.2.3-py3-none-any.whl.metadata (7.8 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Using cached jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.19.0 (from jupyterlab->jupyter)
  Downloading jupyter_server-2.21.1-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Downloading jupyterlab_server-2.28.1-py3-none-any.whl.metadata (5.8 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: anyio in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.15.1)
Collecting certifi (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.20)
Requirement already satisfied: h11>=0.16 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading nbformat-5.11.1-py3-none-any.whl.metadata (3.7 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.26.0-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty!=3.0.4,>=2.0.1 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached pywinpty-3.0.5-cp313-cp313-win_amd64.whl.metadata (5.9 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading websocket_client-1.9.2-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached json5-0.15.0-py3-none-any.whl.metadata (37 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting requests>=2.31 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading argon2_cffi_bindings-26.1.0-cp310-abi3-win_amd64.whl.metadata (7.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=3.0.3->jupyterlab->jupyter)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Collecting attrs>=22.2.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached rpds_py-2026.6.3-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading python_json_logger-4.2.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: pyyaml>=5.3 in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached bleach-6.4.0-py3-none-any.whl.metadata (32 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.3.4-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Using cached nbclient-0.11.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading webencodings-0.6.1-py3-none-any.whl.metadata (3.4 kB)
Collecting tinycss2>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached tinycss2-1.5.1-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading fastjsonschema-2.22.2-py3-none-any.whl.metadata (2.1 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached charset_normalizer-3.5.1-cp313-cp313-win_amd64.whl.metadata (46 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached cffi-2.1.1-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert->jupyter)
  Downloading soupsieve-2.10-py3-none-any.whl.metadata (4.4 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 2.1 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/9.6 MB 2.2 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.6 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.6 MB 2.4 MB/s eta 0:00:04
   -------------- ------------------------- 3.4/9.6 MB 3.0 MB/s eta 0:00:03
   --------------- ------------------------ 3.7/9.6 MB 2.9 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.6 MB 2.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.6 MB 3.0 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.6 MB 3.0 MB/s eta 0:00:02
   --------------------------- ------------ 6.6/9.6 MB 3.0 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.6 MB 3.0 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.6 MB 3.0 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.6 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.6 MB 2.8 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.6 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 2.5 MB/s  0:00:04
Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl (12.6 MB)
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading ipywidgets-8.1.9-py3-none-any.whl (140 kB)
Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
Downloading widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 2.9 MB/s eta 0:00:01
   -------------- ------------------------- 0.8/2.2 MB 2.4 MB/s eta 0:00:01
   ------------------ --------------------- 1.0/2.2 MB 2.2 MB/s eta 0:00:01
   -------------------------------- ------- 1.8/2.2 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 2.4 MB/s  0:00:00
Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Downloading jupyterlab-4.6.4-py3-none-any.whl (17.2 MB)
   ---------------------------------------- 0.0/17.2 MB ? eta -:--:--
   - -------------------------------------- 0.8/17.2 MB 4.0 MB/s eta 0:00:05
   --- ------------------------------------ 1.6/17.2 MB 4.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.6/17.2 MB 4.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.6/17.2 MB 4.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.6/17.2 MB 4.4 MB/s eta 0:00:04
   ---- ----------------------------------- 2.1/17.2 MB 1.6 MB/s eta 0:00:10
   ------- -------------------------------- 3.1/17.2 MB 2.1 MB/s eta 0:00:07
   --------- ------------------------------ 3.9/17.2 MB 2.3 MB/s eta 0:00:06
   ---------- ----------------------------- 4.7/17.2 MB 2.5 MB/s eta 0:00:06
   ------------ --------------------------- 5.5/17.2 MB 2.6 MB/s eta 0:00:05
   -------------- ------------------------- 6.3/17.2 MB 2.7 MB/s eta 0:00:04
   ---------------- ----------------------- 7.1/17.2 MB 2.9 MB/s eta 0:00:04
   ------------------ --------------------- 8.1/17.2 MB 3.0 MB/s eta 0:00:04
   -------------------- ------------------- 8.9/17.2 MB 3.0 MB/s eta 0:00:03
   --------------------- ------------------ 9.2/17.2 MB 2.9 MB/s eta 0:00:03
   ---------------------- ----------------- 9.7/17.2 MB 2.9 MB/s eta 0:00:03
   ----------------------- ---------------- 10.0/17.2 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 10.2/17.2 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 10.2/17.2 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 10.2/17.2 MB 2.8 MB/s eta 0:00:03
   ------------------------- -------------- 10.7/17.2 MB 2.5 MB/s eta 0:00:03
   --------------------------- ------------ 11.8/17.2 MB 2.6 MB/s eta 0:00:03
   ----------------------------- ---------- 12.8/17.2 MB 2.7 MB/s eta 0:00:02
   ------------------------------- -------- 13.6/17.2 MB 2.7 MB/s eta 0:00:02
   --------------------------------- ------ 14.4/17.2 MB 2.8 MB/s eta 0:00:01

In [41]:
!python -m pip install charset-normalizer

Requirement already satisfied: charset-normalizer in e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Lib\site-packages (3.5.1)

In [17]:
import sys

print(sys.executable)

import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\.venv\Scripts\python.exe
Pandas: 3.0.6
NumPy: 2.5.3

In [19]:
from pathlib import Path
import pandas as pd
import numpy as np


# Project root
PROJECT_ROOT = Path.cwd().parent

# Raw dataset
DATA_PATH = (
    PROJECT_ROOT
    / "resources"
    / "raw"
    / "Ajio Fashion Clothing.csv"
)

print("Project root:")
print(PROJECT_ROOT)

print("\nDataset path:")
print(DATA_PATH)

print("\nExists:", DATA_PATH.exists())

Project root:
e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ

Dataset path:
e:\AI-ML ENGINEERING\PORTFOLIO-PROJECTS\ProductIQ\resources\raw\Ajio Fashion Clothing.csv

Exists: True

In [20]:
# Load a small sample for initial profiling

df_sample = pd.read_csv(
    DATA_PATH,
    nrows=1000
)

print("Sample loaded successfully.")
print("Shape:", df_sample.shape)

Sample loaded successfully.
Shape: (1000, 9)

In [26]:
df_sample.head()

,Product_URL,Brand,Description,Id_Product,URL_image,Category_by_gender,Discount Price (in Rs.),Original Price (in Rs.),Color
0,https://www.ajio.com/netplay-checked-polo-t-sh...,netplay,Checked Polo T-shirt,441137362002,https://assets.ajio.com/medias/sys_master/root...,Men,559,699,white
1,https://www.ajio.com/netplay-tapered-fit-flat-...,netplay,Tapered Fit Flat-Front Trousers,441124497006,https://assets.ajio.com/medias/sys_master/root...,Men,720,"1,499",navy
2,https://www.ajio.com/the-indian-garage-co-stri...,the-indian-garage-co,Striped Slim Fit Shirt with Patch Pocket,460453612003,https://assets.ajio.com/medias/sys_master/root...,Men,495,"1,649",white
3,https://www.ajio.com/performax-heathered-crew-...,performax,Heathered Crew-Neck T-shirt,441036730003,https://assets.ajio.com/medias/sys_master/root...,Men,329,599,charcoal
4,https://www.ajio.com/john-players-jeans-washed...,john-players-jeans,Washed Skinny Fit Jeans with Whiskers,441128531011,https://assets.ajio.com/medias/sys_master/root...,Men,899,999,jetblack

In [22]:
df_sample.columns.tolist()

['Product_URL',
 'Brand',
 'Description',
 'Id_Product',
 'URL_image',
 'Category_by_gender',
 'Discount Price (in Rs.)',
 'Original Price (in Rs.)',
 'Color']

In [23]:
print("Rows sampled:", len(df_sample))
print("Columns:", len(df_sample.columns))

print("\nColumns:")
for column in df_sample.columns:
    print("-", column)

Rows sampled: 1000
Columns: 9

Columns:
- Product_URL
- Brand
- Description
- Id_Product
- URL_image
- Category_by_gender
- Discount Price (in Rs.)
- Original Price (in Rs.)
- Color

In [24]:
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product_URL              1000 non-null   str
 1   Brand                    1000 non-null   str
 2   Description              1000 non-null   str
 3   Id_Product               1000 non-null   int64
 4   URL_image                1000 non-null   str
 5   Category_by_gender       1000 non-null   str
 6   Discount Price (in Rs.)  1000 non-null   str
 7   Original Price (in Rs.)  1000 non-null   str
 8   Color                    1000 non-null   str
dtypes: int64(1), str(8)
memory usage: 70.4 KB

In [27]:
print(df_sample.columns.tolist())

['Product_URL', 'Brand', 'Description', 'Id_Product', 'URL_image', 'Category_by_gender', 'Discount Price (in Rs.)', 'Original Price (in Rs.)', 'Color']

In [25]:
missing = (
    df_sample.isnull()
    .sum()
    .to_frame("missing_count")
)

missing["missing_percentage"] = (
    missing["missing_count"]
    / len(df_sample)
    * 100
)

missing.sort_values(
    "missing_percentage",
    ascending=False
)

                         missing_count  missing_percentage
Product_URL                          0                 0.0
Brand                                0                 0.0
Description                          0                 0.0
Id_Product                           0                 0.0
URL_image                            0                 0.0
Category_by_gender                   0                 0.0
Discount Price (in Rs.)              0                 0.0
Original Price (in Rs.)              0                 0.0
Color                                0                 0.0

In [28]:
print(
    "Completely duplicated rows:",
    df_sample.duplicated().sum()
)

Completely duplicated rows: 0

In [29]:
print(
    "Duplicate product IDs:",
    df_sample["Id_Product"].duplicated().sum()
)

Duplicate product IDs: 0

In [30]:
df_sample["Id_Product"].nunique()

1000

In [35]:
print("Discount Price:")
print(df_sample["Discount Price (in Rs.)"].head(20).to_string())

print("\nOriginal Price:")
print(df_sample["Original Price (in Rs.)"].head(20).to_string())

Discount Price:
0     559
1     720
2     495
3     329
4     899
5     684
6     700
7     419
8     374
9     500
10    490
11    675
12    335
13    849
14    559
15    779
16    779
17    503
18    212
19    719

Original Price:
0       699
1     1,499
2     1,649
3       599
4       999
5     1,849
6     2,499
7       499
8       499
9     1,998
10    1,749
11    1,499
12      399
13      999
14      699
15    1,299
16    1,299
17      599
18      299
19      799

In [36]:
print(
    df_sample["Category_by_gender"]
    .value_counts(dropna=False)
    .head(20)
)

Category_by_gender
Men    1000
Name: count, dtype: int64

In [37]:
print(
    df_sample["Brand"]
    .value_counts(dropna=False)
    .head(20)
)

Brand
netplay                       250
teamspirit                    118
dnmx                          114
the-indian-garage-co          100
performax                      75
levis                          57
dennislingo-premium-attire     27
lee-cooper                     25
john-players-jeans             18
campus-sutra                   17
adidas                         16
u-s-polo-assn-                 16
superdry                       13
dillinger                      10
fort-collins                   10
john-players                    9
nike                            9
puma                            8
spykar                          8
hubberholme                     7
Name: count, dtype: int64

In [38]:
print(
    df_sample["Color"]
    .value_counts(dropna=False)
    .head(20)
)

Color
blue          138
black          94
navy           90
white          72
grey           56
olive          45
jetblack       37
green          36
maroon         30
khaki          29
red            25
darkblue       25
yellow         18
ltblue         17
ltgrey         14
beige          14
offwhite       14
darkgrey       12
mediumblue     11
ecru           11
Name: count, dtype: int64

In [39]:
print("Rows:", len(df_sample))

print(
    "Unique product IDs:",
    df_sample["Id_Product"].nunique()
)

print(
    "Duplicate product IDs:",
    df_sample["Id_Product"].duplicated().sum()
)

Rows: 1000
Unique product IDs: 1000
Duplicate product IDs: 0

#COMPLETE DATASET

In [43]:
from charset_normalizer import from_path

result = from_path(DATA_PATH)

for match in result:
    print(
        "Encoding:", match.encoding,
        "| Language:", match.language,
        "| Chaos:", match.percent_chaos
    )

Encoding: cp1250 | Language: English | Chaos: 0.0
Encoding: cp1252 | Language: English | Chaos: 0.0
Encoding: cp1254 | Language: English | Chaos: 0.0
Encoding: cp1257 | Language: English | Chaos: 0.0
Encoding: cp1258 | Language: English | Chaos: 0.0
Encoding: cp775 | Language: English | Chaos: 0.0
Encoding: cp850 | Language: English | Chaos: 0.0
Encoding: cp852 | Language: English | Chaos: 0.0
Encoding: cp1006 | Language: Farsi | Chaos: 0.0
Encoding: cp1125 | Language: Russian | Chaos: 0.0

In [44]:
df = pd.read_csv(
    DATA_PATH,
    encoding="cp1252"
)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (367172, 9)

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 367172 entries, 0 to 367171
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Product_URL              367172 non-null  str
 1   Brand                    367172 non-null  str
 2   Description              367172 non-null  str
 3   Id_Product               367172 non-null  int64
 4   URL_image                367172 non-null  str
 5   Category_by_gender       367172 non-null  str
 6   Discount Price (in Rs.)  367172 non-null  str
 7   Original Price (in Rs.)  367172 non-null  str
 8   Color                    367172 non-null  str
dtypes: int64(1), str(8)
memory usage: 25.2 MB

In [46]:
df.head()

,Product_URL,Brand,Description,Id_Product,URL_image,Category_by_gender,Discount Price (in Rs.),Original Price (in Rs.),Color
0,https://www.ajio.com/netplay-checked-polo-t-sh...,netplay,Checked Polo T-shirt,441137362002,https://assets.ajio.com/medias/sys_master/root...,Men,559,699,white
1,https://www.ajio.com/netplay-tapered-fit-flat-...,netplay,Tapered Fit Flat-Front Trousers,441124497006,https://assets.ajio.com/medias/sys_master/root...,Men,720,"1,499",navy
2,https://www.ajio.com/the-indian-garage-co-stri...,the-indian-garage-co,Striped Slim Fit Shirt with Patch Pocket,460453612003,https://assets.ajio.com/medias/sys_master/root...,Men,495,"1,649",white
3,https://www.ajio.com/performax-heathered-crew-...,performax,Heathered Crew-Neck T-shirt,441036730003,https://assets.ajio.com/medias/sys_master/root...,Men,329,599,charcoal
4,https://www.ajio.com/john-players-jeans-washed...,john-players-jeans,Washed Skinny Fit Jeans with Whiskers,441128531011,https://assets.ajio.com/medias/sys_master/root...,Men,899,999,jetblack

In [47]:
with open(DATA_PATH, "rb") as f:
    f.seek(102619 - 50)
    raw_bytes = f.read(150)

print(raw_bytes)

b'with Insert Pockets,441134790008,https://assets.ajio.com/medias/sys_master/root/20220408/swzj/624f3720f997dd03e24df374/-286Wx359H-441134790-grey-MODEL'

In [48]:
print("Total rows:", len(df))

print(
    "Unique product IDs:",
    df["Id_Product"].nunique()
)

print(
    "Duplicate product IDs:",
    df["Id_Product"].duplicated().sum()
)

Total rows: 367172
Unique product IDs: 367172
Duplicate product IDs: 0

In [49]:
print(
    "Exact duplicate rows:",
    df.duplicated().sum()
)

Exact duplicate rows: 0

In [50]:
missing = (
    df.isnull()
    .sum()
    .to_frame("missing_count")
)

missing["missing_percentage"] = (
    missing["missing_count"] / len(df) * 100
)

missing

                         missing_count  missing_percentage
Product_URL                          0                 0.0
Brand                                0                 0.0
Description                          0                 0.0
Id_Product                           0                 0.0
URL_image                            0                 0.0
Category_by_gender                   0                 0.0
Discount Price (in Rs.)              0                 0.0
Original Price (in Rs.)              0                 0.0
Color                                0                 0.0

In [51]:
print(
    df["Discount Price (in Rs.)"]
    .head(20)
    .to_string(index=False)
)

print("\nOriginal Price:")

print(
    df["Original Price (in Rs.)"]
    .head(20)
    .to_string(index=False)
)

559
720
495
329
899
684
700
419
374
500
490
675
335
849
559
779
779
503
212
719

Original Price:
  699
1,499
1,649
  599
  999
1,849
2,499
  499
  499
1,998
1,749
1,499
  399
  999
  699
1,299
1,299
  599
  299
  799

In [52]:
print(
    df["Discount Price (in Rs.)"].value_counts().head(20)
)

Discount Price (in Rs.)
480      6768
600      6189
999      4877
1,000    4359
799      4160
899      3905
1,499    3799
599      3794
900      3570
750      3439
699      3229
800      3168
1,299    3018
1,199    2985
1,999    2680
450      2678
500      2591
1,799    2529
1,200    2352
559      2264
Name: count, dtype: int64

In [53]:
brand_counts = (
    df["Brand"]
    .value_counts(dropna=False)
)

print(brand_counts.head(30))

Brand
jolie-robe              8135
max                     5179
puma                    3862
louis-philippe          3505
campus-sutra            3489
superdry                3215
ajio                    3203
clovia                  3142
indie-picks             2956
van-heusen              2922
pothys                  2908
indiweaves              2827
sojanya                 2795
u-s-polo-assn-          2733
marks-spencer           2569
friskers                2462
jack-jones              2200
allen-solly             2096
project-eve             2011
netplay                 1948
the-indian-garage-co    1883
kisah                   1875
dnmx                    1862
tommy-hilfiger          1805
free-authority          1734
pepe-jeans              1726
triveni                 1712
trendyol                1710
aeropostale             1652
vero-moda               1633
Name: count, dtype: int64

In [54]:
print("Unique brands:", df["Brand"].nunique())

Unique brands: 1975

In [63]:
df.isnull()

,Product_URL,Brand,Description,Id_Product,URL_image,Category_by_gender,Discount Price (in Rs.),Original Price (in Rs.),Color
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
367167,False,False,False,False,False,False,False,False,False
367168,False,False,False,False,False,False,False,False,False
367169,False,False,False,False,False,False,False,False,False
367170,False,False,False,False,False,False,False,False,False
367171,False,False,False,False,False,False,False,False,False

In [55]:
category_counts = (
    df["Category_by_gender"]
    .value_counts(dropna=False)
)

print(category_counts.head(30))

print(
    "\nUnique categories:",
    df["Category_by_gender"].nunique()
)

Category_by_gender
Women    211534
Men      155638
Name: count, dtype: int64

Unique categories: 2

In [56]:
color_counts = (
    df["Color"]
    .value_counts(dropna=False)
)

print(color_counts.head(30))

print(
    "\nUnique colors:",
    df["Color"].nunique()
)

Color
blue        49807
black       41683
grey        24952
green       24417
white       23876
pink        20565
navy        20021
multi       19427
red         18203
yellow      17298
maroon      11211
beige        8543
brown        7972
orange       7438
purple       5894
olive        5574
peach        5465
cream        3536
offwhite     2186
indigo       1934
khaki        1897
mustard      1818
navyblue     1568
gold         1431
burgundy     1171
darkblue     1115
teal          943
jetblack      909
ltblue        908
magenta       860
Name: count, dtype: int64

Unique colors: 4296

In [58]:
cardinality = pd.DataFrame({
    "column": df.columns,
    "unique_values": [
        df[col].nunique(dropna=False)
        for col in df.columns
    ]
})

cardinality.sort_values(
    "unique_values",
    ascending=False
)

                    column  unique_values
3               Id_Product         367172
0              Product_URL         365388
4                URL_image         365388
2              Description         105749
6  Discount Price (in Rs.)           5198
7  Original Price (in Rs.)           4539
8                    Color           4296
1                    Brand           1975
5       Category_by_gender              2

In [59]:
if "Description" in df.columns:

    print(df["Description"].head(20).to_string())
    
    print(
        "\nMissing descriptions:",
        df["Description"].isna().sum()
    )

0                               Checked Polo T-shirt
1                    Tapered Fit Flat-Front Trousers
2           Striped Slim Fit Shirt with Patch Pocket
3                        Heathered Crew-Neck T-shirt
4              Washed Skinny Fit Jeans with Whiskers
5                   Slim Fit Shirt with Patch Pocket
6                             Striped Slim Fit Shirt
7                   Track Pants with Contrast Taping
8                   Fastdry Active Crew-Neck T-shirt
9                Pack of 2 Shorts with Insert Pocket
10          Checked Slim Fit Shirt with Patch Pocket
11                         Striped Regular Fit Shirt
12                       Heathered Crew-Neck T-shirt
13                Leaf Print Shirt with Patch Pocket
14                           Leaf Print Polo T-shirt
15    Slim Fit Flat-Front Chinos with Insert Pockets
16       Mid-Rise Flat-Front Cropped Slim Fit Chinos
17                            Heathered Polo T-shirt
18               Mid-Rise Shorts with Insert Pockets
19               Fastdry Active Panelled Track Pants

Missing descriptions: 0

In [61]:
if "Description" in df.columns:

    description_lengths = (
        df["Description"]
        .astype(str)
        .str.len()
    )

    print(description_lengths.describe())

count    367172.000000
mean         32.202031
std           8.371868
min           1.000000
25%          26.000000
50%          31.000000
75%          38.000000
max         120.000000
Name: Description, dtype: float64

In [62]:
for column in ["Product_URL", "URL_image"]:
    
    if column in df.columns:
        
        print(f"\n===== {column} =====")
        
        print(
            df[column]
            .head(10)
            .to_string()
        )

===== Product_URL =====
0    https://www.ajio.com/netplay-checked-polo-t-sh...
1    https://www.ajio.com/netplay-tapered-fit-flat-...
2    https://www.ajio.com/the-indian-garage-co-stri...
3    https://www.ajio.com/performax-heathered-crew-...
4    https://www.ajio.com/john-players-jeans-washed...
5    https://www.ajio.com/dennislingo-premium-attir...
6    https://www.ajio.com/dennislingo-premium-attir...
7    https://www.ajio.com/teamspirit-track-pants-wi...
8    https://www.ajio.com/performax-fastdry-active-...
9    https://www.ajio.com/ardeur-pack-of-2-shorts-w...

===== URL_image =====
0    https://assets.ajio.com/medias/sys_master/root...
1    https://assets.ajio.com/medias/sys_master/root...
2    https://assets.ajio.com/medias/sys_master/root...
3    https://assets.ajio.com/medias/sys_master/root...
4    https://assets.ajio.com/medias/sys_master/root...
5    https://assets.ajio.com/medias/sys_master/root...
6    https://assets.ajio.com/medias/sys_master/root...
7    https://assets.ajio.com/medias/sys_master/root...
8    https://assets.ajio.com/medias/sys_master/root...
9    https://assets.ajio.com/medias/sys_master/root...

In [64]:
# Identity and duplicate checks

print("========== ROW / IDENTITY ==========")

print("Total rows:", len(df))

print(
    "Unique product IDs:",
    df["Id_Product"].nunique()
)

print(
    "Duplicate product IDs:",
    df["Id_Product"].duplicated().sum()
)

print(
    "Exact duplicate rows:",
    df.duplicated().sum()
)


print("\n========== MISSING VALUES ==========")

missing = df.isnull().sum()

print(missing)


print("\n========== EMPTY / WHITESPACE VALUES ==========")

for column in df.columns:
    empty_count = (
        df[column]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(f"{column}: {empty_count}")

========== ROW / IDENTITY ==========
Total rows: 367172
Unique product IDs: 367172
Duplicate product IDs: 0
Exact duplicate rows: 0

========== MISSING VALUES ==========
Product_URL                0
Brand                      0
Description                0
Id_Product                 0
URL_image                  0
Category_by_gender         0
Discount Price (in Rs.)    0
Original Price (in Rs.)    0
Color                      0
dtype: int64

========== EMPTY / WHITESPACE VALUES ==========
Product_URL: 0
Brand: 0
Description: 0
Id_Product: 0
URL_image: 0
Category_by_gender: 0
Discount Price (in Rs.): 0
Original Price (in Rs.): 0
Color: 0

In [65]:
# Price format analysis

discount_price = df["Discount Price (in Rs.)"].astype(str)
original_price = df["Original Price (in Rs.)"].astype(str)

print("========== DISCOUNT PRICE ==========")

print(
    "Contains comma:",
    discount_price.str.contains(",", regex=False).sum()
)

print(
    "Has surrounding whitespace:",
    (discount_price != discount_price.str.strip()).sum()
)

print(
    "Unique values:",
    discount_price.nunique()
)


print("\n========== ORIGINAL PRICE ==========")

print(
    "Contains comma:",
    original_price.str.contains(",", regex=False).sum()
)

print(
    "Has surrounding whitespace:",
    (original_price != original_price.str.strip()).sum()
)

print(
    "Unique values:",
    original_price.nunique()
)

========== DISCOUNT PRICE ==========
Contains comma: 169425
Has surrounding whitespace: 0
Unique values: 5198

========== ORIGINAL PRICE ==========
Contains comma: 300088
Has surrounding whitespace: 0
Unique values: 4539

In [66]:
# Find prices that contain characters other than digits, commas, or whitespace

invalid_discount_format = discount_price[
    ~discount_price.str.fullmatch(r"[\d,\s]+")
]

invalid_original_format = original_price[
    ~original_price.str.fullmatch(r"[\d,\s]+")
]

print("Invalid discount-price formats:", len(invalid_discount_format))
print("Invalid original-price formats:", len(invalid_original_format))

print("\nExamples:")
print(invalid_discount_format.head(20).to_list())
print(invalid_original_format.head(20).to_list())

Invalid discount-price formats: 0
Invalid original-price formats: 0

Examples:
[]
[]

In [68]:
# Convert prices temporarily for validation only
discount_numeric = (
    df["Discount Price (in Rs.)"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(int)
)

original_numeric = (
    df["Original Price (in Rs.)"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(int)
)

print("========== PRICE VALUE VALIDATION ==========")

print("Discount price <= 0:",
      (discount_numeric <= 0).sum())

print("Original price <= 0:",
      (original_numeric <= 0).sum())

print("Discount price > Original price:",
      (discount_numeric > original_numeric).sum())

print("Discount price == Original price:",
      (discount_numeric == original_numeric).sum())

print("Discount price < Original price:",
      (discount_numeric < original_numeric).sum())

========== PRICE VALUE VALIDATION ==========
Discount price <= 0: 0
Original price <= 0: 0
Discount price > Original price: 4
Discount price == Original price: 53574
Discount price < Original price: 313594

In [69]:
print("\n========== PRICE RANGES ==========")

print("Discount price:")
print("Min:", discount_numeric.min())
print("Max:", discount_numeric.max())

print("\nOriginal price:")
print("Min:", original_numeric.min())
print("Max:", original_numeric.max())

========== PRICE RANGES ==========
Discount price:
Min: 81
Max: 230800

Original price:
Min: 99
Max: 230800

In [70]:
suspicious_prices = df.loc[
    discount_numeric > original_numeric,
    [
        "Id_Product",
        "Brand",
        "Description",
        "Discount Price (in Rs.)",
        "Original Price (in Rs.)"
    ]
]

print(suspicious_prices.head(30).to_string(index=False))

  Id_Product    Brand                               Description Discount Price (in Rs.) Original Price (in Rs.)
462983590001 sajasajo  Leaf Print Pure Linen Saree with Tassels                  15,695                  15,694
462983595001 sajasajo  Leaf Print Pure Linen Saree with Tassels                  15,695                  15,694
462975646001 sajasajo          Handloom Silk Saree with Tassels                  14,891                  14,890
461716717001 sajasajo Bengal Handloom Pure Dhakai Jamdani Saree                  17,908                  17,907

In [71]:
discount_percentage = (
    (original_numeric - discount_numeric)
    / original_numeric
    * 100
)

print("========== DISCOUNT PERCENTAGE ==========")

print("Minimum:", discount_percentage.min())
print("Maximum:", discount_percentage.max())

print("\nPercentiles:")
print(
    discount_percentage.quantile(
        [0, 0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99, 1.00]
    )
)

========== DISCOUNT PERCENTAGE ==========
Minimum: -0.00671591672263264
Maximum: 93.99931810433004

Percentiles:
0.00    -0.006716
0.01     0.000000
0.05     0.000000
0.25    24.988884
0.50    49.958299
0.75    59.966639
0.95    71.982773
0.99    80.008895
1.00    93.999318
dtype: float64

In [72]:
print(
    "\nNegative discount percentage:",
    (discount_percentage < 0).sum()
)

Negative discount percentage: 4

In [73]:
print("========== COLOR PROFILING ==========")

print("Number of unique colors:", df["Color"].nunique())

print("\nFirst 100 unique colors:")
print(
    df["Color"]
    .drop_duplicates()
    .head(100)
    .to_list()
)

color_whitespace = (
    df["Color"] != df["Color"].str.strip()
).sum()

print("\nColors with leading/trailing whitespace:", color_whitespace)

========== COLOR PROFILING ==========
Number of unique colors: 4296

First 100 unique colors:
['white', 'navy', 'charcoal', 'jetblack', 'olive', 'black', 'ltblue', 'red', 'mintgreen', 'green', 'ltgrey', 'maroon', 'stone', 'orange', 'beige', 'turquoise', 'mediumblue', 'medgrey', 'greymelange', 'navyblue', 'purple', 'petrol', 'grey', 'brown', 'blue', 'offwhite', 'gunmetal', 'darkolive', 'darkblue', 'pink', 'khaki', 'maroonburg', 'ecru', 'gold', 'burgundy', 'teal', 'yellow', 'aqua', 'tan', 'indigoblue', 'indigo', 'ltgreen', 'assorted', 'darkgrey', 'ltpink', 'multi', '02dx', 'lightblue', 'darkgreen', 'lime', 'mint', 'cream', 'pg5', 'olivegreen', 'tomatored', 'peach', 'anthramelange', 'darkkhaki', 'mustard', 'ecrumelange', 'aquablue', 'tintblue', 'bluemelange', 'coral', '02a', 'blackcharcoal', 'rust', 'blackgrey', 'gray', '4911', '15bg', 'dkaqua', 'darkred', 'tint', '15bb', 's4r', 'limeyellow', '05fb', 'ltmulti', 'odg', 'blackwhite', 'dkblue', '4mk', '33b', 'darkyellow', '17g', 'darknavy', 'skyblue', 'lightgrey', '10r', '475', 'z045', 'multicolour', 'adq', 'n6i', '01c', '66z', 'steelgrey', 'midgrey', 'blackglgrey']

Colors with leading/trailing whitespace: 0

In [74]:
color_lower = df["Color"].str.lower()

print("Original unique colors:", df["Color"].nunique())
print("Case-normalized unique colors:", color_lower.nunique())

print(
    "\nPotential case-only duplicates:",
    df["Color"].nunique() - color_lower.nunique()
)

Original unique colors: 4296
Case-normalized unique colors: 4296

Potential case-only duplicates: 0